baseurl: https://ventapormudanza.netlify.app
title: Venta por Mudanza Providencia
theme: hugo-creative-portfolio-theme
languageCode: es-CL
disqusShortname: ''
googleAnalytics: ''

disableKinds:
  - taxonomy
  - taxonomyTerm
  - RSS
pluralizelisttitles: no

menu:
  main:
    - name: External
#      url: https://example.com

params:
  copyright: '&copy;2021 Coco & Bubu'
  description: Sitio de una pagina para una venta por mudanza en Providencia, Chile
  email: izabela.joann@gmail.com
  hideAutoMenu: no
  navlinks:
    - home: yes
      name: Home
      url: portfolio/
    - name: About
      url: about/
    - name: Get in touch
      url: contact/
  sidebarAbout:
    - I am a creative illustrator and graphic designer with more than 10 years of
      experience.
    - Originally from Toronto, currently based in London.
  social:
    email: izabela.joann@gmail.com
    facebook: full page or profile url in facebook
#    github: full profile url in github
#    gitlab: full profile url in gitlab
#    googleplus: full profile url in googleplus
#    instagram: full profile url in instagram
#    linkedin: full profile url in linkedin
#    stackoverflow: full profile url in stackoverflow
#    twitter: full profile url in twitter
    whatsapp: https://wa.me/56951169934?text=Hola!%20Me%20interesan%20tus%20productos%20en%20venta.%20Cuentame%20mas%20sobre%20...
#    youtube: full profile url in youtube
  style: default
