baseURL: https://example.com
languageCode: es-CL
title: Venta por Mudanza Providencia
Paginate: 1000
googleAnalytics: ''
theme: showcase-hugo-theme
disableKinds:
  - taxonomy
  - taxonomyTerm
  - RSS
pluralizelisttitles: no
params:
  author: Venta por Mudanza Providencia
  description: Nos vamos de Chile y vendemos todo, Ayudanos a difundir! retiro en Providencia, Chile
  copyright: '&copy;2021 Coco & Bubu'
  hideAutoMenu: no
  message: 'Nos vamos de Chile y vendemos todo!  Haz click en un producto para escribirnos por WhatsApp.  Retiro en Providencia, Chile'

menu:
  main:
    - name: About
#      url: https://example.com
social:
  whatsapp: https://wa.me/56983277838?text=Hola!%20Me%20interesan%20tus%20productos%20en%20venta.%20Cuentame%20mas%20sobre%20...
#  facebook: https://facebook.com
#  linkedin: https://linkedin.com
#  twitter: https://twitter.com
  email: izabela.joann@gmail.com

